apiVersion: apps/v1
kind: Deployment
metadata:
  name: zulip
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: zulip
  template:
    metadata:
      labels:
        app: zulip
    spec:
      containers:
        - name: zulip
          image: "{{ .Values.app.image }}"
          ports:
            - containerPort: {{ .Values.app.port }}
          env:
            - name: DATABASE_URL
              value: "postgresql://{{ .Values.postgres.user }}:{{ .Values.postgres.password }}@zulip-postgres:{{ .Values.postgres.port }}/{{ .Values.postgres.database }}"
