apiVersion: apps/v1
kind: Deployment
metadata:
  name: zulip-postgres
spec:
  selector:
    matchLabels:
      app: zulip-postgres
  template:
    metadata:
      labels:
        app: zulip-postgres
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image }}:{{ .Values.postgres.tag }}"
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgres.user }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.password }}
            - name: POSTGRES_DB
              value: {{ .Values.postgres.database }}
          ports:
            - containerPort: {{ .Values.postgres.port }}
