apiVersion: v1
kind: Service
metadata:
  name: zulip
spec:
  type: NodePort
  ports:
    - port: {{ .Values.app.port }}
      targetPort: {{ .Values.app.port }}
      nodePort: {{ .Values.app.nodePort }}
  selector:
    app: zulip
