# Number of n8n pods
replicaCount: 1

image:
  repository: kamasanirohith/n8n
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 5678
  targetPort: 5678

# Persistent storage for workflows, SQLite DB, credentials, etc.
persistence:
  enabled: true
  existingClaim: n8n-pvc   # Make sure this PVC exists
  mountPath: /home/node/.n8n

# n8n configuration
n8n:
  protocol: http
  host: "0.0.0.0"

  # Optional: Enable basic authentication (recommended for exposed services)
  basicAuth:
    enabled: false
    user: admin
    password: admin

  # Optional configuration
  logLevel: info
  timezone: UTC

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
