replicaCount: 1

image:
  repository: kamasanirohith/n8n
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 5678
  targetPort: 5678

persistence:
  enabled: true
  existingClaim: n8n-pvc
  mountPath: /home/node/.n8n

n8n:
  protocol: http
  host: "0.0.0.0"
  basicAuth:
    enabled: false
    user: admin
    password: admin
  logLevel: info
  timezone: UTC

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
