apiVersion: apps/v1
kind: Deployment
metadata:
  name: affine
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: affine
  template:
    metadata:
      labels:
        app: affine
    spec:
      containers:
        - name: affine
          image: "{{ .Values.app.repository }}:{{ .Values.app.tag }}"
          imagePullPolicy: {{ .Values.app.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: {{ .Values.app.port }}
          env:
            - name: DATABASE_URL
              value: "postgresql://{{ .Values.postgres.user }}:{{ .Values.postgres.password }}@affine-postgres:{{ .Values.postgres.port }}/{{ .Values.postgres.database }}"
            - name: REDIS_SERVER_HOST
              value: "affine-redis"
            - name: AFFINE_INDEXER_ENABLED
              value: "false"
