apiVersion: v1
kind: Service
metadata:
  name: affine-postgres
spec:
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}
  selector:
    app: affine-postgres
